app/models/image.py
from app import database as db
from app.utils.utils import generate_shortcode
from app.utils.image_compress import Decoder, Encoder, decompress, compressor


class Codes(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.LargeBinary)
    short_code = db.Column(db.String(150))


class DATABASE:
    @staticmethod
    def get_shortcode_from_code(code):
        data = Codes.query.filter_by(code=code).first()
        return data.short_code

    @staticmethod
    def store_image(image):
        all_short_code = [i.short_code for i in Codes.query.all()]
        all_code = [i.code for i in Codes.query.all()]
        encoder = Encoder(image)
        compressed_data = compressor(encoder.encoded_string())
        if compressed_data in all_code:
            return DATABASE.get_shortcode_from_code(compressed_data)
        short_code = generate_shortcode(all_short_code)
        code = Codes(code=compressed_data, short_code=short_code)
        db.session.add(code)
        db.session.commit()

        return short_code

    @staticmethod
    def get_image_from_shortcode(code):
        data = Codes.query.filter_by(short_code=code).first()
        if data is None:
            return "404"
        decompressed_data = decompress(data.code)
        decoder = Decoder(decompressed_data)
        return decoder.response()

    @staticmethod
    def get_all_images():
        images = []
        for i in Codes.query.all():
            data = {"link": f"/image/{i.short_code}", "code": i.short_code}
            images.append(data)
        return images

app/views/auth.py
from flask import Blueprint
from flask import render_template
from flask import redirect
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_user
from flask_login import logout_user

from app.models.users import DB
from app.models.users import User

bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/login", methods=["POST", "GET"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("todo.todo_index"))
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")
        user = User.query.filter_by(username=username).first()
        if user is None or not user.check_password(password):
            return render_template("login.html", message="Username Not Found")
        login_user(user)
        return redirect(url_for("todo.todo_index"))

    return render_template("login.html", title="Login")


@bp.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")
        email = request.form.get("email")
        if username in DB.all_users():
            return render_template(
                "register.html", title="Register", message="Username Already Found"
            )
        if email in DB.all_email():
            return render_template(
                "register.html", title="Register", message="Email Already Found"
            )
        DB.add_user(username, password, email)
        return render_template("login.html", message="Register Successfully")
    return render_template("register.html", title="Register")


@bp.route("/logout")
def logout():
    logout_user()
    return render_template("index.html", message="Logout Successfully")

app/views/fun.py
from flask import Blueprint
from flask import request
from flask import render_template
from flask import jsonify

from app.utils.flames import flames_for
from app.utils.countdown import new_year
from app.utils.countdown import india_zone
from app.utils.countdown import count_down

bp = Blueprint("fun", __name__, url_prefix="/fun")


@bp.route("/flames", methods=["GET", "POST"])
def flames():
    if request.method == "POST":
        p1 = request.form.get("p1")
        p2 = request.form.get("p2")
        result = flames_for(p1, p2)
        return render_template(
            "flames.html", game=result, title="Flames", signal=result["result"][0]
        )
        print(result["result"][0])
    return render_template("flames.html", title="Flames")


@bp.route("/new-year-countdown")
def countdown():
    return render_template("new_year.html", year=new_year)


@bp.route("/time")
def lapse():
    tz = request.args.get("tz")
    if tz is None:
        return jsonify(count_down(india_zone))
    else:
        return jsonify(count_down(tz))


@bp.route("/dice")
def dice():
    return render_template("dice.html")

app/views/github.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for

from app.utils.github_utils import UserStats
from app.utils.plots import pie_chart

bp = Blueprint("github", __name__, url_prefix="/github")


@bp.route("/<username>")
def github_stats_render(username):
    possible_query = [
        "repos_per_langs",
        "star_per_langs",
        "commit_per_repo",
        "star_per_repo",
    ]
    query = request.args.get("q")
    user = UserStats(username)
    if query in possible_query:
        data = user.__getattribute__(query)()
        return pie_chart(data, query)
    links = [f"/github/{username}?q={i}" for i in possible_query]
    return render_template(
        "github.html", name=user.name, links=links, title=user.name, stats=user.stats(), username=username
    )


@bp.route("/", methods=["GET", "POST"])
def home_render():
    if request.method == "POST":
        username = request.form.get("username")
        return redirect(url_for("github.github_stats_render", username=username))
    return render_template("github_index.html")

app/views/image.py
from urllib.parse import urlparse

from flask import Blueprint
from flask import request
from flask import render_template

from app.models.image import DATABASE
from config import Configuartion

bp = Blueprint("image", __name__, url_prefix="/image")


@bp.route("/upload", methods=["GET", "POST"])
def image_upload():
    if request.method == "POST":
        file = request.files["file"]
        source = Configuartion.UPLOAD_DIR + f"/{file.filename}"
        file.save(source)
        code = DATABASE.store_image(source)
        host_components = urlparse(request.host_url)
        host_base = host_components.scheme + "://" + host_components.netloc
        return render_template(
            "image.html",
            url=f"{host_base}/image/{code}",
            message="Image uploaded Sucessfully",
        )
    return render_template(
        "image.html", title="Free Image Hosting", images=DATABASE.get_all_images()
    )


@bp.route("/<code>")
def render_image(code):
    return DATABASE.get_image_from_shortcode(code)

app/views/redirecter.py
from flask import Blueprint, redirect, request, render_template

from app.utils.utils import generate_seq
from urllib.parse import urlparse

bp = Blueprint("redirecter", __name__, url_prefix="/redirecter")


@bp.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        link = request.form.get("link")
        times = request.form.get("times")
        host_components = urlparse(request.host_url)
        host_base = host_components.scheme + "://" + host_components.netloc
        return render_template(
            "redirecter.html",
            url=f"{host_base}/redirecter/redirect?link={link}&times={times}",
            title="Redirecting Tool",
        )
    return render_template("redirecter.html", title="Redirecting Tool")


@bp.route("/redirect")
def redirecter():
    link = request.args.get("link")
    times = request.args.get("times")

    return redirect(f"redirecting?link={link}&times={times}")


@bp.route("/<fake>")
def fake_router(fake):
    link = request.args.get("link")
    times = int(request.args.get("times"))

    if times == 1:
        return redirect(link)

    else:
        times = times - 1
        code = generate_seq()

        return redirect(f"{code}?times={times}&link={link}")

app/views/todo.py
from flask import Blueprint
from flask import render_template
from flask import redirect
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required

from app.models.users import DB

bp = Blueprint("todo", __name__, url_prefix="/todo")


@bp.route("/", methods=["POST", "GET"])
@login_required
def todo_index():
    return render_template("todo.html", message="Logged In Successfully")


@login_required
@bp.route("/task/add", methods=["GET", "POST"])
def todo_add():
    if request.method == "POST":
        task = request.form.get("task")
        DB.add_todo(current_user.username, task)
        return redirect(url_for("todo.todo_index"))
    return redirect(url_for("todo.todo_index"))


@login_required
@bp.route("/task/remove")
def todo_remove():
    task = request.args.get("task")
    DB.remove_todo(current_user.username, task)
    return redirect(url_for("todo.todo_index"))

app/views/tools.py
from flask import Blueprint
from flask import request
from flask import render_template

from app.utils.mask_url import MaskUrl
from app.utils.mask_url import Shortner
from app.utils.age import parse_html_date
from app.utils.age import Age

bp = Blueprint("tools", __name__, url_prefix="/tools")


@bp.route("/maskurl", methods=["GET", "POST"])
def mask_url():
    if request.method == "POST":
        turl = request.form.get("turl")
        hurl = request.form.get("hurl")
        kw = request.form.get("kw")
        try:
            masked_url = MaskUrl(turl, hurl, kw)
            return render_template("mask_url.html", url=masked_url, title="Mask Url")
        except KeyError:
            return render_template("mask_url.html", url="Incorrect Url")
    return render_template("mask_url.html", title="Mask Url")


@bp.route("/shorturl", methods=["GET", "POST"])
def short_url():
    if request.method == "POST":
        turl = request.form.get("url")
        shorted_url = Shortner(turl)
        return render_template("short_url.html", url=shorted_url, title="Short Url")
    return render_template("short_url.html", title="Short Url")


@bp.route("/age", methods=["GET"])
def age_cal():
    date = request.args.get("date")
    if date:
        d_ = parse_html_date(date)
        return render_template(
            "age.html",
            age=Age(*d_).age(),
            title="Age Calculator",
            q="{}-{}-{}".format(*list(map(lambda x: str(x).zfill(2), d_))),
        )
    return render_template("age.html", title="Age Calculator")

app/templates/age.html
{% extends 'base.html' %} {% block ref %}
<style>
    body {
        display: block;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
    }
    
    .form {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
    }
    
    .datetime {
        margin: 30px;
        position: relative;
        overflow: hidden;
    }
    
    .day {
        font-size: 64px;
    }
</style>
{% endblock ref %} {% block content %}
<h1 style="text-align: center; color:darkgreen">Age Calculator</h1>
<div class="form">
    <input type="date" id='date_p' class="input-group input-group-lg form">
    <br>
    <button type="submit" class="btn btn-success form" id="btn">Check</button>
</div>

{% if age %}
<div class="datetime" style="text-align: center;">
    <div class="day" style="text-align: center;">{{ q }}</div>
    <h4 class="date">{{ age.weekday }}</h4>
</div>
<div class="card" style="width: 100%; max-width: 300px; display: block; margin:auto">
    <div class="card" style="max-width: 330px; display: block; margin:auto">
        <div class="card-body">
            <h5 class="card-title" style="text-align: center;">Age</h5>
            <ul>
                <h6 class="card-subtitle mb-2 text-muted" style="font-size: xx-large;">{{ age.year }} <span class="card-subtitle mb-2 text-muted" style="font-size: medium;">Years</span></h6>
                <h6 class="card-subtitle mb-2 text-muted" style="font-size: xx-large;">{{ age.months }} <span class="card-subtitle mb-2 text-muted" style="font-size: medium;">Months</span></h6>
                <h6 class="card-subtitle mb-2 text-muted" style="font-size: xx-large;">{{ age.days }} <span class="card-subtitle mb-2 text-muted" style="font-size: medium;">Days</span></h6>
            </ul>
        </div>
    </div>
</div>
<br>
<div class="card" style="width: 100%; max-width: 300px; display: block; margin:auto">
    <div class="card" style="max-width: 330px; display: block; margin:auto">
        <div class="card-body">
            <h5 class="card-title" style="text-align: center;">Summary</h5>
            <ul>
                <h6 class="card-subtitle mb-2 text-muted" style="font-size: xx-large;">{{ age.as_months }} <span class="card-subtitle mb-2 text-muted" style="font-size: medium;">Months</span></h6>
                <h6 class="card-subtitle mb-2 text-muted" style="font-size: xx-large;">{{ age.as_weeks }} <span class="card-subtitle mb-2 text-muted" style="font-size: medium;">Weeks</span></h6>
                <h6 class="card-subtitle mb-2 text-muted" style="font-size: xx-large;">{{ age.as_days }} <span class="card-subtitle mb-2 text-muted" style="font-size: medium;">Hours</span></h6>
                <h6 class="card-subtitle mb-2 text-muted" style="font-size: xx-large;">{{ age.as_hours }} <span class="card-subtitle mb-2 text-muted" style="font-size: medium;">Minutes</span></h6>
                <h6 class="card-subtitle mb-2 text-muted" style="font-size: xx-large;">{{ age.as_minutes }} <span class="card-subtitle mb-2 text-muted" style="font-size: medium;">Weeks</span></h6>
                <h6 class="card-subtitle mb-2 text-muted" style="font-size: xx-large;">{{ age.as_seconds }} <span class="card-subtitle mb-2 text-muted" style="font-size: medium;">Seconds</span></h6>
            </ul>
        </div>
    </div>
</div>
{% endif %} {% endblock content %} {% block script %}
<script src="{{ url_for('static', filename='js/age_script.js') }}"></script>
{% endblock script %}

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://getbootstrap.com/docs/5.0/dist/css/bootstrap.min.css" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>{{ title }} | Fun Web Projects</title>
    {% block ref %} {% endblock ref %}
</head>

<body>
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="https://github.com/yogeshwaran01/Fun-Web-Projects">Fun Web Projects</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('todo.todo_index') }}">My Tasks</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <br>
    <br> {% if message %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert" id="message">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button> {{ message }}
    </div>
    {% endif %}
    <br> {% block content %} {% endblock content %}
    <footer class="footer">
        <div class="container">
            <span class="text-muted" style="text-align: center;">Coded by <a
                    href="https://yogeshwaran01.github.io">yogeshwaran01</a></span>
        </div>
    </footer>
    {% block script %} {% endblock script %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/popper.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.0/dist/js/bootstrap.min.js"></script>
</body>

</html>

app/templates/flames.html
{% extends 'base.html' %} {% block ref %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/flames_style.css') }}"> {% endblock ref %} {% block content %} {% if game %}
<div class="hit-the-floor">
    {% if signal == "f" %}
    <span class="diff">F</span>LAMES {% elif signal == "l" %} F
    <span class="diff">L</span>AMES {% elif signal == "a" %} FL
    <span class="diff">A</span>MES {% elif signal == "m" %} FLA
    <span class="diff">M</span>ES {% elif signal == "e" %} FLAM
    <span class="diff">E</span>S {% elif signal == "s" %} FLAME
    <span class="diff">S</span> {% else %} FLAMES {% endif %}

</div>
<h1 class="thickness">{{ game.result.upper() }}</h1>
<div class="center">
    <p class="text-center" style="font-size: xx-large;">{{ game.p1.upper() }}</p>
    <p class="text-center" style="font-size: xx-large;">{{ game.p2.upper() }}</p>
</div>

{% else %}
<div class="hit-the-floor">
    FLAMES
</div>
{% endif %}

<div class="container">

    <form class="center" method="POST" action="{{ url_for('fun.flames') }}">

        <div class="group">
            <input type="text" required name="p1">
            <span class="highlight"></span>
            <span class="bar"></span>
            <label>Player 1</label>
        </div>

        <div class="group">
            <input type="text" required name="p2">
            <span class="highlight"></span>
            <span class="bar"></span>
            <label>Player 2</label>
        </div>

        <button type="submit" class="btn btn-success center">Check</button>

    </form>

</div>
{% endblock content %}

app/templates/github.html
{% extends 'base.html' %} {% block ref %}
<style>
    #thumbnails img,
    #main {
        box-shadow: 2px 2px 10px 5px #b8b8b8;
        border-radius: 10px;
    }
    
    * {
        transition: all 0.5s ease;
    }
    
    #thumbnails img {
        width: 100px;
        height: 100px;
        margin: 10px;
        cursor: pointer;
    }
    
    @media only screen and (max-width: 480px) {
        #thumbnails img {
            width: 50px;
            height: 50px;
        }
    }
    
    #thumbnails img:hover {
        transform: scale(1.05);
    }
    
    #main {
        display: block;
        margin: 20px auto;
    }
</style>
{% endblock ref %} {% block content %}
<h1 style="text-align: center;">{{ name }}</h1>
<h6 style="text-align: center; color: red;">Open Image in new Tab for best experience</h6>
<img src="https://github-stats-terminal-style.herokuapp.com/{{ username }}" id='main' alt=""> {% for link in links %}
<img src="{{ link }}" id="main" width="800" height="800">
</div>
{% endfor %} {% endblock content %}

app/templates/github_index.html
{% extends 'base.html' %} {% block ref %}
<link rel="stylesheet" href="{{url_for('static', filename='css/login_style.css')}}"> {% endblock ref %} {% block content %}
<div class="form-signin">
    <form action="{{ url_for('github.home_render') }}" method="POST">
        <h1 class="h3 mb-3 fw-normal" style="text-align: center;">Github Stats</h1>
        <input type="text" id="inputTurl" class="form-control" placeholder="Username" required autofocus name="username">
        <br>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Get Stats</button>
    </form>
</div>
{% endblock content %}

app/templates/image.html
{% extends 'base.html' %} {% block ref %}
<style>
    .form {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
    }
</style>
{% endblock ref %} {% block content %}
<h1 style="text-align: center; color:darkgreen">Upload Image to Free Host</h1>
<h3 style="text-align: center; color:darkgreen">Size must less than 1MB</h3>
<form class="form" action="" method="POST" enctype=multipart/form-data>
    <div class="mb-3">
        <input type="file" class="form-control" aria-label="file example" required name="file">
        <div class="invalid-feedback">Load the Image First</div>
        <br>
        <button type="submit" class="btn btn-success form" id="btn">Upload</button>
    </div>
</form>
{% if url %}
<h4>Your image Hosted at</h4>
<div class="alert alert-success" role="alert">
    <h4>{{ url }}</h4>
</div>
{% endif %}
<div class="container">
    <div class="row">
        {% for image in images %}
        <div class="col-sm-6">
            <div class="card" style="width: 100%;">
                <img src="{{ image.link }}" class="card-img-top" alt="{{ image.code }}">
                <div class="card-body">
                    <p class="card-text" style="text-align: center;">{{ image.code }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

app/templates/index.html
{% extends 'base.html' %} {% block content %}
<div class="container" style="width: auto;">
    <div class="d-grid gap-2 col-6 mx-auto">
        <button type="button" class="btn btn-success" onclick="location.href = '/todo'">Task Management</button>
        <button type="button" class="btn btn-success" onclick="location.href = '/tools/maskurl'">Mask The Link</button>
        <button type="button" class="btn btn-success" onclick="location.href = '/tools/shorturl'">URL Shorting
            Tool</button>
        <button type="button" class="btn btn-success" onclick="location.href = '/tools/age'">Age Calculator</button>
        <button type="button" class="btn btn-success" onclick="location.href = '/fun/flames'">Flames</button>
        <button type="button" class="btn btn-success" onclick="location.href = '/image/upload'">Free Image Hosting</button>
        <button type="button" class="btn btn-success" onclick="location.href = '/fun/new-year-countdown'">New Year Countdown</button>
        <button type="button" class="btn btn-success" onclick="location.href = '/github/'">Github Stats</button>
        <button type="button" class="btn btn-success" onclick="location.href = '/redirecter/'">Redirecting Tool</button>
    </div>
</div>
{% endblock content %}

app/templates/login.html
{% extends 'base.html' %} {% block ref %}
<link rel="stylesheet" href="{{url_for('static', filename='css/login_style.css')}}"> {% endblock ref %} {% block content %}
<div class="form-signin">
    <form action="/auth/login" method="POST">
        <h1 class="h3 mb-3 fw-normal" style="text-align: center;">Please sign in</h1>
        <label for="inputEmail" class="visually-hidden">Username</label>
        <input type="text" id="inputEmail" class="form-control" placeholder="Username" required autofocus name="username">
        <br>
        <label for="inputPassword" class="visually-hidden">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name="password">
        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
        <br>
        <br>
        <a href="/auth/register" class="btn btn-primary" style="justify-content: center; display:block; width: 100px; margin: 0 auto;">Register</a>
    </form>
</div>
{% endblock content %}

app/templates/mask_url.html
{% extends 'base.html' %} {% block ref %}
<link rel="stylesheet" href="{{url_for('static', filename='css/login_style.css')}}"> {% endblock ref %} {% block content %}
<div class="form-signin">
    <form action="{{ url_for('tools.mask_url') }}" method="POST">
        <h1 class="h3 mb-3 fw-normal" style="text-align: center;">MaskUrl</h1>
        <input type="url" id="inputTurl" class="form-control" placeholder="Target Link" required autofocus name="turl">
        <div class="row-fluid show-grid" style="text-align: right;">
            <div class="span6" style="color: red;"> <span style="color: black;">Example: </span> https://ngrok.io/idf
            </div>
        </div>

        <input type="url" id="inputHurl" class="form-control" placeholder="URL to Mask Target" required name="hurl">
        <div class="row-fluid show-grid" style="text-align: right;">
            <div class="span6" style="color: red;"> <span style="color: black;">Example:
                </span>https://instagram.com</div>
        </div>
        <input type="text" id="kw" placeholder="Key Word" class="form-control" name="kw">
        <div class="row-fluid show-grid" style="text-align: right;">
            <div class="span6" style="color: red;"> <span style="color: black;">Example: </span>free-instagram-likes
            </div>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Get Mask Url</button>
        <div class="row-fluid show-grid">
            <span id="error">
            </span>
        </div>
        <br> {% if url %}
        <div class="alert alert-success" role="alert">
            {{ url }}
        </div>
        {% endif %}
    </form>
</div>
{% endblock content %} {% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    var text = document.getElementById('error').innerHTML
    $(function() {
        $('#kw').on('keypress', function(e) {
            if (e.which == 32) {
                text = "Don' user spacest";
                return false;
            }
        });
    });
</script>
{% endblock script %}

app/templates/new_year.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Year</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/new_year.css')}}" />
    <script src="{{url_for('static', filename='js/new_year.js')}}"></script>
</head>

<body>
    <div class="container">
        <h1>
            <a href="https://github.com/yogeshwaran01/new-year-countdown-python/">
                Countdown New Year
            </a>
        </h1>
        <div>
            <ul>
                <li><span id="days"></span>days</li>
                <li><span id="hours"></span>Hours</li>
                <li><span id="minutes"></span>Minutes</li>
                <li><span id="secs"></span>Seconds</li>
            </ul>
            <h1>{{ year }}</h1>
        </div>
    </div>
</body>

</html>

app/templates/redirecter.html
{% extends 'base.html' %} {% block ref %}
<link rel="stylesheet" href="{{url_for('static', filename='css/login_style.css')}}"> {% endblock ref %} {% block content %}
<div class="form-signin">
    <form action="{{ url_for('redirecter.index') }}" method="POST">
        <h1 class="h3 mb-3 fw-normal" style="text-align: center;">Redirect the link</h1>
        <input type="url" id="inputUrl" class="form-control" placeholder="Link" required autofocus name="link">
        <br>
        <input type="number" id="inputNumber" class="form-control" placeholder="How many times to redirect" required autofocus name="times">
        <br>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Get Redirecting Link</button>
        <br>
        <br> {% if url %}
        <div class="alert alert-success" role="alert">
            {{ url }}
        </div>
        {% endif %}
    </form>
</div>
{% endblock content %}

app/templates/short_url.html
{% extends 'base.html' %} {% block ref %}
<link rel="stylesheet" href="{{url_for('static', filename='css/login_style.css')}}"> {% endblock ref %} {% block content %}
<div class="form-signin">
    <form action="{{ url_for('tools.short_url') }}" method="POST">
        <h1 class="h3 mb-3 fw-normal" style="text-align: center;">Make Link Shorter</h1>
        <input type="url" id="inputUrl" class="form-control" placeholder="Link" required autofocus name="url">
        <br>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Short Link</button>
        <br>
        <br> {% if url %}
        <div class="alert alert-success" role="alert">
            {{ url }}
        </div>
        {% endif %}
    </form>
</div>
{% endblock content %}

app/templates/todo.html
{% extends 'base.html' %} {% block ref %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/todo_style.css') }}"> {% endblock ref %} {% block content %}

<h2 style="text-align: center;">{{current_user.username}}'s Tasks</h2>

<br>

<div class="containers">
    <br>
    <h2 style="text-align: center;">
        TODO LIST
    </h2>
    <br>
    <div class="input-group mb-3">
        <form action="task/add" class="input-group mb-3" method="POST">
            <input type="text" class="form-control" id="task" placeholder="Add Task" name="task">
            <button class="btn btn-outline-secondary" type="submit" id="but">Add</button>
        </form>
    </div>

    <ul class="list-group list-group-flush">
        {% for todo in current_user.todos %}
        <li class="list-group-item">
            <span>{{ todo }}</span>
            <button type="button" value="{{ todo }}" class="btn btn-danger" style="float: right;" onclick="location.href='task/remove?task={{ todo }}'">Delete</button>
        </li>
        {% endfor %}
    </ul>
</div>

<br>

<a id="link" href="{{ url_for('auth.logout') }}" class="link-danger" style="justify-content: center; display:block; width: 100px; margin: 0 auto;">Logout</a> {% endblock %} {% block script %} {% endblock script %}